# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{reverse_captcha}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Lopes"]
  s.date = %q{2010-08-13}
  s.description = %q{Simple reverse captcha solution that consist in create a hidden field that should be always empty.}
  s.email = %q{danielvlopes@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/reverse_captcha.rb",
     "lib/reverse_captcha/model.rb",
     "lib/reverse_captcha/view.rb",
     "reverse_captcha.gemspec",
     "test/schema.rb",
     "test/support/comment.rb",
     "test/support/mock_controller.rb",
     "test/support/mock_response.rb",
     "test/test_helper.rb",
     "test/test_model.rb",
     "test/test_view.rb"
  ]
  s.homepage = %q{http://github.com/danielvlopes/reverse_captcha}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{simple solution for reverse captcha in Rails apps}
  s.test_files = [
    "test/schema.rb",
     "test/support/comment.rb",
     "test/support/mock_controller.rb",
     "test/support/mock_response.rb",
     "test/test_helper.rb",
     "test/test_model.rb",
     "test/test_view.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

